### ISSUE TITLE
HALO24 fail with v5.1.4-ov51

### ISSUE THREAD

**Issue by electronsailor** [opencpn-radar-pi/radar_pi#156] opened 2020-11-29 16:14 UTC
Unable to get A or B to properly initialize with radarpi v5.1.4-ov51 and two different up to date Windows 10 computers, though everything works swimmingly on a RPI4 running OpenCPN 5.2.4 and radarpi v5.1.4.

To begin with, the PPI for Halo A does not show up. The PPI for Halo B does show up. Selecting other Navico radar types is equally unsuccessful.

Thanks

![radarpi1](https://user-images.githubusercontent.com/75214468/100547249-b49f6d00-3233-11eb-9d70-9f0607e64af3.jpg)

**Comment by keesverruijt** [comment] 2020-11-29 17:45
Actually you can see it has found something on Halo A, the serial # is filled in. But it is still showing Scanning Interface.

If you use the context menu, can you ask it to show radar A control menu and then do "Show" there? It's probably just hidden.

**Comment by electronsailor** [comment] 2020-11-29 18:02
Yes, you are right. I can pull up the PPI for Halo A, but it still shows "No Radar" even though it has found the serial#. Simultaneously, the Zeus3 and the RPI both operate and view Halo A and Halo B normally.

**Comment by keesverruijt** [comment] 2020-12-11 12:30
We hope to fix this in an upcoming beta. I will update this once this is available.

**Comment by keesverruijt** [comment] 2021-02-15 14:04
We think this was caused by a hardwired check for serial numbers.

**Comment by electronsailor** [comment] 2021-02-15 14:47
Kees - Thank you. Douwe provided me with a preliminary radarpi that
bypassed serial number check and works with my Halo24.  Thanks for your
work on this!
Chip

**Comment by alorman** [comment] 2021-03-09 20:11
Piling onto this thread. Is it possible to post or email a release that bypasses the serial # check?
Thank you!

**Comment by Hakansv** [comment] 2021-03-10 07:15
@alorman 
We're working to release the beta version but the plugin upload process to OCPN plugin manager has a malfunction.
Meanwhile... If are you on Windows try this: [radar_pi v.5.2.0.beta4](https://www.dropbox.com/s/w8bgfnf56mmtez8/radar_pi-5.2.0-beta4-ov51-msvc-10.0.19042.exe?dl=1)
You know you have to uninstall a possible managed plugin in OCPN->Options->Plugins and restart O before a unmanaged plugin will be loaded?

**Comment by keesverruijt** [comment] 2021-03-11 13:24
v5.2.0-beta4 which fixes this is now available in the catalog. Enjoy! Please close this issue if this release fixes the problem for you.

**Comment by alorman** [comment] 2021-03-11 14:05
Can confirm! Thanks to everyone on this project for the awesome work

**Closed** 2021-03-11 14:17 UTC
