### ISSUE TITLE
GarminxHD : Gray areas when increasing range.

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#21] opened 2017-11-12 22:37 UTC
This refers to the PPI only. It looks like the plot memory is reset when you go to a lower range but not when you go to a higher. I have uploaded a recording, ice_video_20171112-174324.webm  to my dropbox.

**Comment by canboat** [comment] 2017-11-13 07:46
The intended behaviour is that the target trails are zoomed in and out when you change range, e.g. in both directions.

**Comment by canboat** [comment] 2017-11-13 08:15
Hans, can you share your dropbox with Douwe so he can take a look?

**Comment by trudK45** [comment] 2017-11-13 11:07
I  think I already have done that. Did you try Douwe ?

**Comment by canboat** [comment] 2017-11-18 13:37
I get weird results with trails as well, on Windows they seem to appear at strange times and on macOS they don't disappear if I set them to a low # of seconds.

**Comment by douwefokkema** [comment] 2017-11-20 08:43
I have access to your dropbox, using Scan1 most of the time. Is there a pcap where I can see this issue (pcap with zooming on it) so I can replay this issue. I do not need a video.

**Comment by trudK45** [comment] 2017-11-20 10:41
Jobs done.
I have uploaded a .pcap to my dropbox., Gray_areas.zip

**Comment by douwefokkema** [comment] 2017-11-21 09:04
Thanks, I will work with it right now.

**Comment by douwefokkema** [comment] 2017-11-22 09:08
This issue is identical to #18. See there for further reactions.

**Comment by douwefokkema** [comment] 2017-11-23 08:44
Hans reports that grey areas are no longer there. Close this issue. Further remarks on trails under #18

**Closed by douwefokkema** 2017-11-23 08:44 UTC
